### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by unterumarmung** [PopovEvgeniy/SWGF#1]
1. КодБлоксом не надо пользоваться и тем более его билд системой, испльзуй CMake
2.  `constexpr` переменные и функции
https://github.com/PopovEvgeniy/SWGF/blob/e73ae127e0da1a8cb1ceb291b87d2fe264a9784e/source/tilemap.cpp#L3-L4
https://github.com/PopovEvgeniy/SWGF/blob/e73ae127e0da1a8cb1ceb291b87d2fe264a9784e/source/SWGF.h#L70-L85

3. Переменные надо объявлять в месте их первого использования, а не заранее
https://github.com/PopovEvgeniy/SWGF/blob/e73ae127e0da1a8cb1ceb291b87d2fe264a9784e/source/tilemap.cpp#L13-L16
https://github.com/PopovEvgeniy/SWGF/blob/e73ae127e0da1a8cb1ceb291b87d2fe264a9784e/source/tilemap.cpp#L28-L32
4. ```int main(void)```: `void` не нужен

5. `enum class` вместо `enum`
https://github.com/PopovEvgeniy/SWGF/blob/e73ae127e0da1a8cb1ceb291b87d2fe264a9784e/source/SWGF.h#L87-L94

5. Зачем префиксы, если можно поместить в namespace?
https://github.com/PopovEvgeniy/SWGF/blob/e73ae127e0da1a8cb1ceb291b87d2fe264a9784e/source/SWGF.h#L99-L173

6. Зачем использовать битовые поля? Экономия ради экономии? Как говорится:
> Premature optimization is the root of all evil

7. Для размеров следует использовать `std::size_t` вместо `unsigned long int` - как минимум читать проще

8. Не `NULL`, а `nullptr`
https://github.com/PopovEvgeniy/SWGF/blob/e73ae127e0da1a8cb1ceb291b87d2fe264a9784e/source/SWGF.cpp#L205

9. Умные указатели, а не ручное управление памятью
https://github.com/PopovEvgeniy/SWGF/blob/e73ae127e0da1a8cb1ceb291b87d2fe264a9784e/source/SWGF.cpp#L324

10. Не самый консистентный кодстайл - рекомендую посмотреть в сторону clang-format

11. Почитать на досуге: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines

**Comment by PopovEvgeniy** [comment]
Спасибо что уделили время.
Отвечаю по пунктам.

**Comment by PopovEvgeniy** [comment]
Спасибо что уделили время.
Отвечаю по пунктам.

1. Дело вкуса.
2. Код расчитан на старые компиляторы без поддержки C++ 11.
3. Дело вкуса.
4. Вы правы.
5. Смотрите пункт 2.
6. Вы правы, учту.
7. Битовые поля нужны чтобы размер структур не поехал при компиляции под другую разрядность.
8. Смотрите пункт 2.
9. Смотрите пункт 2.
10. Спасибо. Постараюсь учесть но все же дело вкуса.

**Comment by unterumarmung** [comment]
1. Конечно, дело вкуса, но если планируется, что этим кто-то будет пользоваться - то использовать Code::Blocks - недружелюбно
2. Тогда надо использовать `const`-переменные. Константные переменные, проинициализированные constant expression, так же являются константами времени компиляции. 
А зачем поддерживать старые компиляторы?
3. Конечно дело вкуса, но: чем больше область видимости переменной - тем больше вероятность получить ошибку.
7. Зачем? Как размер `char` уедет при портации на другую разрядность? По стандарту С++ `sizeof(char) == 1`, но при этом `CHAR_BIT >= 8`
10. Я не говорю про сам код стайл - плохой он или хороший. Я говорю, что он неконсистентный - это по-умолчанию плохо.

**Comment by PopovEvgeniy** [comment]
1. А чем собственно плох Code::Blocks?
2. Подумаю над const. Мысль хорошая. Старые компиляторы надо поддерживать потому что минимальная версия Windows - XP.
3. Фикситься внимательностью.
4. Без битовых полей структурные поля отличные от char поедут при смене разрядности.
5. Как вы видите консистентность?

**Comment by PopovEvgeniy** [comment]
Учел часть ваших замечаний

**Comment by PopovEvgeniy** [comment]
Учел часть ваших замечаний

**Comment by PopovEvgeniy** [comment]
Учел часть ваших замечаний

**Comment by PopovEvgeniy** [comment]
Учел часть ваших замечаний

**Comment by PopovEvgeniy** [comment]
Учел часть ваших замечаний

**Comment by PopovEvgeniy** [comment]
Учел часть ваших замечаний

**Comment by unterumarmung** [comment]
1. Для этого есть список инициализации в конструкторах
https://github.com/PopovEvgeniy/SWGF/blob/06adfe45cc773a6fcc839c3f4005957bba6f2147/source/SWGF.cpp#L468-L476
2. Мне кажется стоит не писать все классы в одном файле, а всё-таки их разделить - читаемость улучшится
3. В чем проблема написать на одной строчке?
https://github.com/PopovEvgeniy/SWGF/blob/06adfe45cc773a6fcc839c3f4005957bba6f2147/source/SWGF.cpp#L664-L665
4. Внимательность - плохой аргумент, человек не обладает ей всегда. В большинстве случаев он ей не обладает. На свой мозг и свою память надеяться не стоит.
5. Зачем делать отдельную функцию для инициализации, если есть конструктор?
https://github.com/PopovEvgeniy/SWGF/blob/06adfe45cc773a6fcc839c3f4005957bba6f2147/source/SWGF.cpp#L2749-L2755
6. В С++ так делать над объектами не стоит
https://github.com/PopovEvgeniy/SWGF/blob/06adfe45cc773a6fcc839c3f4005957bba6f2147/source/SWGF.cpp#L2779-L2780
7. Рекомендую прогнать код под статическими анализаторами (clang-tidy, cppcheck, PVS-studio)
8. Пример код стайла, который мне в целом нравится, можно например почитать здесь: https://clickhouse.tech/docs/ru/development/style/
Его писали не дураки, знают о чем говорят

**Comment by PopovEvgeniy** [comment]
Огромное спасибо за уделенное время
